@startuml
title SD – US12 List All Vaccines
autoactivate on
autonumber

actor "Administrator" as User
participant ":ListVaccinesView" as System
participant ":ListVaccinesController" as Ctrl
participant ":Administrator" as Admin
participant "service:VaccineService" as Service
participant "factory:RepositoryFactory" as Factory
participant "repo:VaccineRepository" as Repo
participant "list:List<Vaccine>" as List
participant "vac:Vaccine" as Vac
participant "type:VaccineType" as Type

activate User

User -> System: asks to list all vaccines
System -> Ctrl: getAllGrouped()
Ctrl -> Admin: getVaccineService()
Admin -> Factory : getVaccineRepository()
Factory --> Admin: repo
Admin --> Service**: create(repo)
Admin --> Ctrl: service

Ctrl -> Service: getAllGroupedByBrand()
Service -> Repo: findAll()
Repo --> Service: list
note right: Service sorts and groups list \nby Type and Brand (AC12-1)
Service --> Ctrl: list
Ctrl --> System: list

loop for each 'vac' in 'list'
    System -> Vac: getBrand()
    Vac --> System: brand
    System -> Vac: getCommercialName()
    Vac --> System: commercialName
    System -> Vac: getType()
    Vac -> Type: getDisease()
    Type --> Vac: disease
    Vac --> System: disease
    System --> User: shows disease, brand and commercial name
end loop

@enduml