@startuml
' US10-SSD.puml
' Baseado na estrutura da imagem.png (template USXX-SSD.puml)

title US10 - Specify a new vaccine type

autoactivate on
autonumber

' Mapeado de User -> Administrator
actor "Administrator" as Admin
' Mapeado de :System
participant ":System" as System

activate Admin

' Mapeado de "Authentication request"
Admin -> System: requests to specify a new vaccine type

' Mapeado de "Authentication response"
System --> Admin: requests data (code, description)

' Mapeado de "Another authentication request"
Admin -> System: provides data

' Mapeado de "Another authentication response"
System --> Admin: informs operation success

deactivate Admin
@enduml