@startuml
' US10-MD.puml
' Baseado na estrutura da imagem.png (template USXX-DM.puml )

title US10 - Domain Model

hide circle
skinparam classAttributeIconSize 0
hide methods

' Mapeado de Concept1  -> DGSAdministrator
class DGSAdministrator {
    - name: String
}

' Mapeado de Concept2  -> VaccineType
' Atributos baseados nos requisitos da US10 (code, description)
class VaccineType {
    - code: String
    - description: String
}

' Mapeado da associação "1 knows 0..*"
DGSAdministrator "1" -> "0..*" VaccineType : specifies >

@enduml