@startuml
' https://plantuml.com/class-diagram
title US13 - Domain Model
skinparam classAttributeIconSize 0
hide circle
hide methods

' ===================== Administrator =====================
class DGSAdministrator {
    - name
    - email
}

' ===================== Vaccination Centers =====================
abstract class VaccinationCenter {
    - name
    - postalAddress
    - phone
    - email
    - website
    - maxVaccinesPerHour
    - openingHours
    - closingHours
}

class HealthcareCenter
class CommunityMassVaccinationCenter

VaccinationCenter <|-- HealthcareCenter
VaccinationCenter <|-- CommunityMassVaccinationCenter

' ===================== Vaccine Type =====================
class VaccineType {
    - disease
    - shortDescription
}

' ===================== Associations =====================

DGSAdministrator "1" -- "0..*" VaccinationCenter : registers >

CommunityMassVaccinationCenter "1" -- "1..*" VaccineType : administers >

VaccinationCenter "1" -- "0..*" VaccineType : supports >

@enduml
