@startuml
autoactivate on
autonumber

participant "Receptionist" as Actor
participant ":HTTPClient" as Client
participant ":HTTPServer" as Server
participant "req:HTTPRequest" as Request
participant "resp:HTTPResponse" as Response
participant "handler:RouteHandler" as System
participant ":ApiController" as Ctrl
participant ":Receptionist" as Role
participant "service:VaccineScheduleService" as Service
participant "factory:RepositoryFactory" as Factory
participant "repo:VaccineScheduleRepository" as Repo
participant "schedule:VaccineSchedule" as Entity
participant "result:HttpResult" as Result

activate Actor

Actor -> Client: asks to update a vaccine schedule
Client -> Server: PUT /vaccine-schedules/{id} ({json_data})
Server -> Request**: create(..., {json_data})
Server -> Response**: create(404)
Server -> Server: findHandler(req)
Server -> System: run(req, resp)

System -> Ctrl: putVaccineSchedule(id, json_data)

' Obtendo o serviço através do objeto de domínio Receptionist
Ctrl -> Role: getVaccineScheduleService()
Role -> Factory: getVaccineScheduleRepository()
Factory --> Role: repo
Role --> Service**: create(repo)
Role --> Ctrl: service

' Lógica de atualização
Ctrl -> Service: update(id, data)
Service -> Repo: getById(id)
Repo --> Service: schedule
Service -> Entity: update(data)
Service -> Service: validate(schedule)
note right: Valida se o centro tem vaga na nova hora
Service --> Service: ok
Service -> Repo: save(schedule)
Repo --> Service: ok
Service --> Ctrl: updatedSchedule

Ctrl -> Result**: create(200, updatedSchedule)
Ctrl --> System: result
System -> System: setHttpResult(resp, result)
System --> Server: resp
Server --> Client: resp
Client --> Actor: informs success
@enduml