@startuml
'https://plantuml.com/sequence-diagram

title US15 - System Sequence Diagram (List Employees by Role)

autoactivate on
autonumber

actor "Administrator" as ADM
participant ":System" as System

activate ADM

ADM -> System: Request list of employees by role (role)
System --> ADM: Show list of employees for given role

@enduml
