@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0
hide methods

title US15 - Domain Model (List Employees by Role)

abstract StaffMember {
    -name
    -postalAddress
    -phone
    -email
}

class Receptionist extends StaffMember
class Nurse extends StaffMember
class DGSAdministrator extends StaffMember

@enduml
