@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam classAttributeIconSize 0

class RegisterSNSUserView {
}

class RegisterSNSUserController {
    +registerSNSUser(name, address, sex, phone, email, birth, snsNumber, ccNumber): void
    +saveRegisteredSNSUser(): Result
}

class Receptionist {
    - name
    +getSNSUserService(): SNSUserService
}

class SNSUserService {
    +SNSUserService(SNSUserRepository repo)
    +create(name, address, sex, phone, email, birth, snsNumber, ccNumber): SNSUser
    +addOrUpdate(SNSUser user): Result
    -validate(SNSUser user): boolean
}

interface SNSUserRepository <<interface>> {
    +save(SNSUser user): Result
    +findByPhone(phone): SNSUser
    +findByEmail(email): SNSUser
    +findBySNSNumber(snsNumber): SNSUser
    +findByCCNumber(ccNumber): SNSUser
}

interface RepositoryFactory <<interface>> {
    +getSNSUserRepository(): SNSUserRepository
}

class SNSUser {
    - name: String
    - address: String
    - sex: String
    - phone: String
    - email: String
    - birthDate: Date
    - snsNumber: String
    - ccNumber: String
    +SNSUser(name, address, sex, phone, email, birth, snsNumber, ccNumber)
}

Receptionist "1" -down-> "1" RepositoryFactory: uses
SNSUserRepository "1" -right-> "0..*" SNSUser: records

RegisterSNSUserView ..> RegisterSNSUserController
RegisterSNSUserController ..> Receptionist
RegisterSNSUserController ..> SNSUserService
SNSUserService ..> SNSUserRepository
SNSUserService ..> SNSUser
RegisterSNSUserController ..> SNSUser

Receptionist -> SNSUserService: adopts
RepositoryFactory .right.> SNSUserRepository

@enduml