@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

actor "Receptionist" as User
participant ":RegisterSNSUserView" as System
participant ":RegisterSNSUserController" as Ctrl
participant ":Receptionist" as Receptionist
participant "service:SNSUserService" as Service
participant "factory:RepositoryFactory" as Factory
participant "repo:SNSUserRepository" as Repo
participant "snsUser:SNSUser" as SNSUser

activate User

User -> System: asks to register a new SNS user
System --> User: requests data (name, address, sex, phone, e-mail, birth, snsNumber, ccNumber)

User -> System: types requested data
'Nota: Não usamos DTO, passamos os atributos diretamente
System -> Ctrl: registerSNSUser(name, address, sex, phone, e-mail, birth, snsNumber, ccNumber)

'Aplicação do Repository & Service Pattern com Abstract Factory
Ctrl -> Receptionist: getSNSUserService()
Receptionist -> Factory : getSNSUserRepository()
Factory --> Receptionist: repo
Receptionist --> Service**: create(repo)
Receptionist --> Ctrl: service

'Criação da entidade SNSUser
Ctrl -> Service: create(name, address, sex, phone, e-mail, birth, snsNumber, ccNumber)
Service --> SNSUser**: create(name, address, sex, phone, e-mail, birth, snsNumber, ccNumber)
Service --> Ctrl: snsUser

Ctrl --> System: ok
System --> User: shows all data and requests confirmation

User -> System: confirms the data
System -> Ctrl: saveRegisteredSNSUser()

'Separação de responsabilidades: Service valida, Repository guarda
Ctrl -> Service: addOrUpdate(snsUser)
Service -> Service : validate(snsUser)
note right: Validação de unicidade (AC20-3) e formatos (AC20-1)
Service --> Service : ok

Service -> Repo: save(snsUser)
Repo --> Service : ok
Service --> Ctrl: ok
Ctrl --> System: ok
System --> User: informs operation success
@enduml