@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
hide circle
hide methods

class Receptionist {
    - name
}

class SNSUser {
    - name
    - address
    - sex
    - phoneNumber
    - email
    - birthDate
    - snsNumber
    - citizenCardNumber
}

Receptionist "1" -right-- "0..*" SNSUser:  registers >

@enduml