@startuml
title US14 - Sequence Diagram

autoactivate on
autonumber

actor "Administrator" as Admin
participant ":RegisterEmployeeUI" as UI
participant ":RegisterEmployeeController" as Ctrl
participant ":Company" as Comp
participant "store:EmployeeStore" as Store
participant "emp:StaffMember" as Emp

activate Admin

Admin -> UI: asks to register a new employee
UI --> Admin: requests data

Admin -> UI: types data (name, address, phone, email, ccNum)
UI --> Admin: requests role

Admin -> UI: selects role (roleId)
UI -> Ctrl: createEmployee(dto)

Ctrl -> Comp: getEmployeeStore()
Comp --> Ctrl: store

Ctrl -> Store: createEmployee(dto)
    Store -> Store: validateUniqueness(email, phone)
    note right
      Checks if email/phone
      already exist in the list
    end note

    Store -> Emp: create(name, address, phone, email, ccNum)
        Emp -> Emp: validateData()
        note right
           AC14-2 (Mandatory)
           AC14-3 (PT Format)
        end note
    Emp --> Store: emp
Store --> Ctrl: emp

Ctrl --> UI: emp
UI --> Admin: shows data and requests confirmation

Admin -> UI: confirms
UI -> Ctrl: saveEmployee()
Ctrl -> Store: saveEmployee(emp)
    Store -> Store: add(emp)
    Store --> Ctrl: ok
Ctrl --> UI: ok
UI --> Admin: success

@enduml