@startuml
title US14 - Domain Model

hide methods
hide circle
skinparam classAttributeIconSize 0


abstract class StaffMember {
  - name
  - postalAddress
  - phone
  - email
  - citizenCardNumber
}

class Receptionist extends StaffMember
class Nurse extends StaffMember
class DGSAdministrator extends StaffMember




@enduml