@startuml
title SSD – US41 Record Vaccine Administration

autoactivate on
autonumber

actor "Nurse" as Nurse
participant ":System" as System

activate Nurse

Nurse -> System: asks to record a vaccine administration
System --> Nurse: shows vaccines list and requests data

Nurse -> System: provides requested data
System --> Nurse: shows all data and requests confirmation

Nurse -> System: confirms the data
System --> Nurse: informs operation success and user transition to recovery state

@enduml