@startuml
'https://plantuml.com/class-diagram
left to right direction

hide circle
skinparam classAttributeIconSize 0

class RegisterArrivalController {
  +postArrivalPreview(RegisterArrivalRequestDTO req) : HttpResult
  +postConfirmCheckIn(string appointmentId) : HttpResult
  +getCheckIn(string checkInId) : HttpResult
  +putCheckIn(string checkInId, json payload) : HttpResult
  +deleteCheckIn(string checkInId) : HttpResult
}

class HttpResult {
  -status : HttpStatus
  -result : json
  HttpResult()
  HttpResult(HttpStatus status)
  HttpResult(HttpStatus status, const wstring &message)
  HttpResult(HttpStatus status, const string &message)
  HttpResult(HttpStatus status, const char *message)
  HttpResult(HttpStatus status, const json &result)
}

RegisterArrivalController ..> HttpResult

@enduml
