@startuml
autoactivate on
autonumber
title REST API – US22 – DELETE (DELETE /check-ins/{checkInId})

participant ":HTTPClient" as HTTPClient
participant "handler:RouteHandler" as System
participant ":CheckInController" as Ctrl
participant ":Receptionist" as Receptionist
participant "service:CheckInService" as Service
participant "factory:RepositoryFactory" as Factory
participant "repo:CheckInRepository" as Repo
participant "result:HttpResult" as Result

activate HTTPClient

HTTPClient -> System: DELETE /check-ins/{checkInId}\nAuthorization
System -> System: validateAuth()
System -> System: parsePath()

System -> Ctrl: deleteCheckIn(checkInId)

Ctrl -> Receptionist: getCheckInService()
Receptionist -> Factory: getCheckInRepository()
Factory --> Receptionist: repo
Receptionist --> Service**: create(repo)
Receptionist --> Ctrl: service

Ctrl -> Service: remove(checkInId)
Service -> Repo: remove(checkInId)
Repo --> Service: removed?

alt not found
  Service --> Ctrl: notFound()
  Ctrl --> Result**: create(404)
else deleted
  Service --> Ctrl: ok()
  Ctrl --> Result**: create(204)
end

Ctrl --> System: result
System -> System: setHttpResult(resp, result)
System --> HTTPClient: resp

@enduml
