@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

title US40 - SD

actor "Nurse" as NurseActor
participant ":ConsultWaitingRoomView" as UI
participant ":ConsultWaitingRoomController" as Ctrl
participant ":Nurse" as Nurse
participant "service:CheckInService" as Service
participant "factory:RepositoryFactory" as Factory
participant "repo:CheckInRepository" as Repo
participant "checkIn:CheckIn" as CheckIn
participant "user:SNSUser" as User

activate NurseActor

NurseActor -> UI: asks to consult the waiting room list
UI --> NurseActor: requests the selection of the vaccination center

NurseActor -> UI: selects the requested vaccination center
UI -> Ctrl: getWaitingRoomList(center)

' Obtenção do serviço via Nurse/Factory (Seguindo o Molde)
Ctrl -> Nurse: getCheckInService()
Nurse -> Factory : getCheckInRepository()
Factory --> Nurse: repo
Nurse --> Service**: create(repo)
Nurse --> Ctrl: service

' Obtenção da lista ordenada
Ctrl -> Service: getWaitingRoomList(center)
note right: AC40-1: Logic to sort by arrival time
Service -> Repo: findByCenter(center)
Repo --> Service: List<CheckIn>
Service --> Ctrl: List<CheckIn>
Ctrl --> UI: List<CheckIn>

UI --> NurseActor: shows the waiting list and requests confirmation to view

' Iteração sobre os dados após confirmação
NurseActor -> UI: confirms the view
loop for each checkIn in list
    UI -> CheckIn: getSNSUser()
    CheckIn --> UI: user
    UI -> User: getName()
    User --> UI: name
    UI -> User: getSnsUserNumber()
    User --> UI: snsNumber
    UI --> NurseActor: displays name + snsNumber
end loop

@enduml