@startuml
hide circle
title US40 - CD
skinparam classAttributeIconSize 0

class ConsultWaitingRoomView {
}

class ConsultWaitingRoomController {
    +getWaitingRoomList(center): List<CheckIn>
}

class Nurse {
    - email
    +getCheckInService(): CheckInService
}

class CheckInService {
    +CheckInService(CheckInRepository checkInRepo)
    +getWaitingRoomList(center): List<CheckIn>
}

interface CheckInRepository <<interface>> {
    +findByCenter(center): List<CheckIn>
}

interface RepositoryFactory <<interface>> {
    +getCheckInRepository(): CheckInRepository
}

class CheckIn {
    - dateTime
    +getSNSUser(): SNSUser
    +getDateTime(): DateTime
}

class SNSUser {
    - snsUserNumber
    - name
}

Nurse "1" -down-> "1" RepositoryFactory: uses
CheckInRepository "1" -right-> "0..*" CheckIn: records
CheckIn "1" -down-> "1" SNSUser: associated to

ConsultWaitingRoomView ..> ConsultWaitingRoomController
ConsultWaitingRoomView ..> CheckIn
ConsultWaitingRoomController ..> Nurse
ConsultWaitingRoomController ..> CheckInService
CheckInService ..> CheckInRepository

Nurse -> CheckInService: adopts
RepositoryFactory .right.> CheckInRepository

@enduml