@startuml
'https://plantuml.com/class-diagram
left to right direction

hide circle
skinparam classAttributeIconSize 0

title US40 - CD RestAPI

class WaitingRoomController {
    +getWaitingRoomList(centerId: String): HttpResult
}

class WaitingRoomMapper {
    +toJson(CheckIn checkIn): json
    +toJson(List<CheckIn> list): json
}

class HttpResult {
    -status: HttpStatus
    -result: json
    HttpResult();
    HttpResult(HttpStatus status);
    HttpResult(HttpStatus status, const wstring &message);
    HttpResult(HttpStatus status, const string &message);
    HttpResult(HttpStatus status, const char *message);
    HttpResult(HttpStatus status, const json &result);
}

' Relationships based on the template
WaitingRoomController ..> WaitingRoomMapper
WaitingRoomController ..> HttpResult

@enduml